name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint-format-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm ci || npm install

      - name: Run ESLint
        run: npx eslint --max-warnings=0 . || echo "Linting issues found, but continuing"

      - name: Run Prettier check
        run: npx prettier --check "**/*.{js,html,css,json}" || echo "Formatting issues found, but continuing"

      - name: Run tests
        run: npm test || npx jest
